services:
  - type: web
    name: tellbill-backend
    runtime: node
    buildCommand: bash render-build.sh
    startCommand: npm start
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production

