services:
  - type: web
    name: tellbill-backend
    runtime: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: node server_dist/index.js
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production

