#!/usr/bin/env node

/**
 * Postinstall hook to ensure kotlinVersion is present in android/gradle.properties
 * This runs after npm install on EAS build servers to ensure Gradle can find the property
 */

const fs = require('fs');
const path = require('path');

const gradlePropsPath = path.join(__dirname, 'android', 'gradle.properties');

if (fs.existsSync(gradlePropsPath)) {
  const content = fs.readFileSync(gradlePropsPath, 'utf8');
  
  if (!content.includes('kotlinVersion=')) {
    console.log('🔧 Adding kotlinVersion to gradle.properties...');
    fs.appendFileSync(gradlePropsPath, '\n# Kotlin version (added by postinstall.js)\nkotlinVersion=2.0.20\n');
    console.log('✅ Successfully added kotlinVersion=2.0.20 to gradle.properties');
  } else {
    console.log('✅ kotlinVersion already present in gradle.properties');
  }
} else {
  console.log('ℹ️  android/gradle.properties not found yet (will be generated by expo prebuild)');
}
