export const PLAN_LIMITS = {
  free: {
    voiceRecordings: 3,
    invoices: 3,
    projects: 3,
    features: {
      voiceRecording: true,
      basicInvoicing: true,
      emailSupport: true,
      advancedTemplates: false,
      teamManagement: false,
      paymentTracking: false,
      recurringInvoices: false,
      invoiceAutomation: false,
      prioritySupport: false,
      customBranding: false,
      multipleProjects: false,
      advancedAnalytics: false,
      apiAccess: false,
    },
  },
  solo: {
    voiceRecordings: Infinity,
    invoices: Infinity,
    projects: Infinity,
    features: {
      voiceRecording: true,
      basicInvoicing: true,
      emailSupport: true,
      advancedTemplates: true,
      teamManagement: false,
      paymentTracking: true,
      recurringInvoices: true,
      invoiceAutomation: true,
      prioritySupport: false,
      customBranding: true,
      multipleProjects: true,
      advancedAnalytics: true,
      apiAccess: false,
    },
  },
  team: {
    voiceRecordings: Infinity,
    invoices: Infinity,
    projects: Infinity,
    features: {
      voiceRecording: true,
      basicInvoicing: true,
      emailSupport: true,
      advancedTemplates: true,
      teamManagement: true,
      paymentTracking: true,
      recurringInvoices: true,
      invoiceAutomation: true,
      prioritySupport: true,
      customBranding: true,
      multipleProjects: true,
      advancedAnalytics: true,
      apiAccess: false,
    },
  },
  enterprise: {
    voiceRecordings: Infinity,
    invoices: Infinity,
    projects: Infinity,
    features: {
      voiceRecording: true,
      basicInvoicing: true,
      emailSupport: true,
      advancedTemplates: true,
      teamManagement: true,
      paymentTracking: true,
      recurringInvoices: true,
      invoiceAutomation: true,
      prioritySupport: true,
      customBranding: true,
      multipleProjects: true,
      advancedAnalytics: true,
      apiAccess: true,
    },
  },
};

export const PRICING_TIERS = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    period: "forever",
    description: "Perfect for getting started",
    features: [
      "3 voice recordings/month",
      "3 invoices/month",
      "Basic invoicing",
      "Email support",
    ],
    cta: "Current Plan",
    highlighted: false,
  },
  {
    id: "solo",
    name: "Solo",
    price: "$29",
    period: "/month",
    description: "For freelancers & solo contractors",
    features: [
      "Unlimited voice recordings",
      "Unlimited invoices",
      "Advanced templates",
      "Payment tracking",
      "Recurring invoices",
      "Email & chat support",
    ],
    cta: "Upgrade to Solo",
    highlighted: false,
  },
  {
    id: "team",
    name: "Team",
    price: "$99",
    period: "/month",
    description: "Most popular for teams",
    features: [
      "Everything in Solo",
      "Team management",
      "Multiple projects",
      "Priority support",
      "Custom branding",
      "Advanced analytics",
    ],
    cta: "Upgrade to Team",
    highlighted: true,
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Custom",
    period: "pricing",
    description: "For large teams & organizations",
    features: [
      "Everything in Team",
      "API access",
      "Custom integrations",
      "Dedicated support",
      "SSO/SAML",
      "Advanced security",
    ],
    cta: "Contact Sales",
    highlighted: false,
  },
];
